# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cv2
import numpy
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QImage
from PyQt5.QtWidgets import QFileDialog
import matplotlib.pyplot as plt
from copy import deepcopy
from PIL import Image
from math import cos, sin

from DaoAnh import hien_thi_dao_anh
from Bien_Doi_Gamma import hien_thi_gamma
from Bien_Doi_Logarit import hien_thi_logarit
from Bien_Doi_Cat_nguong import hien_thi_cat_nguong
from histogram import histogram


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.DaoAnh = QtWidgets.QPushButton(self.centralwidget)
        self.DaoAnh.setGeometry(QtCore.QRect(220, 120, 221, 91))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.DaoAnh.setFont(font)
        self.DaoAnh.setObjectName("DaoAnh")
        self.DaoAnh.clicked.connect(self.hien_thi_dao_anh)
        
        
        
        self.Logit = QtWidgets.QPushButton(self.centralwidget)
        self.Logit.setGeometry(QtCore.QRect(570, 120, 221, 91))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Logit.setFont(font)
        self.Logit.setObjectName("Logit")
        self.Logit.clicked.connect(self.hien_thi_logarit)
        
        self.Gamma = QtWidgets.QPushButton(self.centralwidget)
        self.Gamma.setGeometry(QtCore.QRect(220, 260, 221, 91))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Gamma.setFont(font)
        self.Gamma.setObjectName("Gamma")
        self.Gamma.clicked.connect(self.hien_thi_gamma)
        
        self.Catnguong = QtWidgets.QPushButton(self.centralwidget)
        self.Catnguong.setGeometry(QtCore.QRect(570, 260, 221, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(19)
        self.Catnguong.setFont(font)
        self.Catnguong.setObjectName("Catnguong")
        self.Catnguong.clicked.connect(self.hien_thi_cat_nguong)

        self.Histogram = QtWidgets.QPushButton(self.centralwidget)
        self.Histogram.setGeometry(QtCore.QRect(220, 400, 221, 91))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Histogram.setFont(font)
        self.Histogram.setObjectName("Histogram")
        self.Histogram.clicked.connect(self.histogram)
        
        self.lbImage = QtWidgets.QLabel(self.centralwidget)
        self.lbImage.setGeometry(QtCore.QRect(160, 40, 781, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lbImage.setFont(font)
        self.lbImage.setObjectName("lbImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DaoAnh.setText(_translate("MainWindow", "Đảo ảnh"))
        self.Logit.setText(_translate("MainWindow", "Logarit"))
        self.Gamma.setText(_translate("MainWindow", "Gamma"))
        self.Catnguong.setText(_translate("MainWindow", "Cắt ngưỡng"))
        self.Histogram.setText(_translate("MainWindow", "Histogram"))
        self.lbImage.setText(_translate("MainWindow", "CHỌN PHÉP TOÁN BẠN MUỐN BIẾN ĐỔI ẢNH"))
        
    #1
    def hien_thi_dao_anh(self):
        hien_thi_dao_anh()
    #2
    def hien_thi_cat_nguong(self):
        hien_thi_cat_nguong()
    #3
    def hien_thi_logarit(self):
        hien_thi_logarit()
    #4
    def hien_thi_gamma(self):
        hien_thi_gamma()
    #5
    def histogram(self):
        histogram()
  
    
    
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
